name: Terraform Validate in Push Origin

on:
    push: #pra cada push presente no repo

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
          - name: Check-code
            uses: actions/checkout@v2
          
          - name: Change Directory
            run: cd terraform-examples
        
          - name: Install depends Terraform
            uses: hashicorp/setup-terraform@v1

          - name: Terraform Validate
            run: terraform validate
            working-directory: ./terraform-examples
            
          - name: Terraform Plan
            run: terraform init && terraform plan
            working-directory: ./terraform-examples