name: Pré requisitos (Obrigatórios)

on: [push]

jobs:
  valida-pre-requisitos: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da última versão do código
      uses: actions/checkout@v2 #  verifica o código do repositório

    - name: Tag Key - Repositorio
      run: |
        if grep -rnil "repositorio" "${{ github.workspace }}" --exclude-dir=.github > resultado_busca.txt; then
          echo "[SUCESSO] Tag Repositorio incluída."
          echo "Encontrada no(s) seguinte(s) arquivo(s):"
          cat resultado_busca.txt
        else
          echo "[ERRO] Tag Repositorio não foi encontrada nos arquivos do repositório. Inclua seguindo a documentação <link>"
          exit 1
        fi

    - name: Tag Key - Servico_Operacional
      run: |
        if grep -rnil "Servico_Operacional" "${{ github.workspace }}" --exclude-dir=.github > resultado_busca.txt; then
          echo "[SUCESSO] Tag Servico_Operacional incluída."
          echo "Encontrada no(s) seguinte(s) arquivo(s):"
          cat resultado_busca.txt
        else
          echo "[ERRO] Tag Servico_Operacional não foi encontrada nos arquivos do repositório. Inclua seguindo a documentação <link>"
          exit 1
        fi

    - name: Tag Key - Tecnologia
      run: |
        if grep -rnil "Tecnologia" "${{ github.workspace }}" --exclude-dir=.github  > resultado_busca.txt; then
          echo "[SUCESSO] Tag Tecnologia incluída."
          echo "Encontrada no(s) seguinte(s) arquivo(s):"
          cat resultado_busca.txt
        else
          echo "[ERRO] Tag Tecnlogia não foi encontrada nos arquivos do repositório. Inclua seguindo a documentação <link>"
          exit 1
        fi

  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Instalando dependências do Terraform
        uses: hashicorp/setup-terraform@v1


      - name: Terraform Init e Validate
        run: |
          cd terraform-examples
          terraform init && terraform validate