name: Pré requisitos (Obrigatórios)

on: [push]

jobs:
  valida-pre-requisitos: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da última versão do código
      uses: actions/checkout@v2 # verifica o código do repositório
      
    - name: Instalação do Python
      uses: actions/setup-python@v2 # instala o python e dependencias
      with:
        python-version: 3.8
    
    - name: Instalação de dependências
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Verificar Presença da Palavra "repositorio" no Código
      run: |
        if grep -rni "repositorio" "${{ github.workspace }}" --exclude-dir=.github --exclude=.github/workflows/*; then
          echo "Sucesso: A palavra 'repositorio' foi encontrada."
        else
          echo "Erro: A palavra 'repositorio' não foi encontrada."
          exit 1
        fi
