name: Pré requisitos (Obrigatórios)

on: [push]

jobs:
  valida-pre-requisitos: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da última versão do código
      uses: actions/checkout@v2 # verifica o código do repositório
      
    - name: Instalação do Python
      uses: actions/setup-python@v2 # instala o python e dependencias
      with:
        python-version: 3.8
    
    - name: Instalação de dependências
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Busca pela Palavra "repositorio"
      run: |
        if ! grep -rni "repositorio" .; then
          echo "Erro: A palavra 'repositorio' não foi encontrada."
          exit 1
        fi